require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ResolversController do

  # This should return the minimal set of attributes required to create a valid
  # Resolver. As you add validations to Resolver, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "device" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResolversController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all resolvers as @resolvers" do
      resolver = Resolver.create! valid_attributes
      get :index, {}, valid_session
      assigns(:resolvers).should eq([resolver])
    end
  end

  describe "GET show" do
    it "assigns the requested resolver as @resolver" do
      resolver = Resolver.create! valid_attributes
      get :show, {:id => resolver.to_param}, valid_session
      assigns(:resolver).should eq(resolver)
    end
  end

  describe "GET new" do
    it "assigns a new resolver as @resolver" do
      get :new, {}, valid_session
      assigns(:resolver).should be_a_new(Resolver)
    end
  end

  describe "GET edit" do
    it "assigns the requested resolver as @resolver" do
      resolver = Resolver.create! valid_attributes
      get :edit, {:id => resolver.to_param}, valid_session
      assigns(:resolver).should eq(resolver)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Resolver" do
        expect {
          post :create, {:resolver => valid_attributes}, valid_session
        }.to change(Resolver, :count).by(1)
      end

      it "assigns a newly created resolver as @resolver" do
        post :create, {:resolver => valid_attributes}, valid_session
        assigns(:resolver).should be_a(Resolver)
        assigns(:resolver).should be_persisted
      end

      it "redirects to the created resolver" do
        post :create, {:resolver => valid_attributes}, valid_session
        response.should redirect_to(Resolver.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved resolver as @resolver" do
        # Trigger the behavior that occurs when invalid params are submitted
        Resolver.any_instance.stub(:save).and_return(false)
        post :create, {:resolver => { "device" => "invalid value" }}, valid_session
        assigns(:resolver).should be_a_new(Resolver)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Resolver.any_instance.stub(:save).and_return(false)
        post :create, {:resolver => { "device" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested resolver" do
        resolver = Resolver.create! valid_attributes
        # Assuming there are no other resolvers in the database, this
        # specifies that the Resolver created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Resolver.any_instance.should_receive(:update_attributes).with({ "device" => "MyString" })
        put :update, {:id => resolver.to_param, :resolver => { "device" => "MyString" }}, valid_session
      end

      it "assigns the requested resolver as @resolver" do
        resolver = Resolver.create! valid_attributes
        put :update, {:id => resolver.to_param, :resolver => valid_attributes}, valid_session
        assigns(:resolver).should eq(resolver)
      end

      it "redirects to the resolver" do
        resolver = Resolver.create! valid_attributes
        put :update, {:id => resolver.to_param, :resolver => valid_attributes}, valid_session
        response.should redirect_to(resolver)
      end
    end

    describe "with invalid params" do
      it "assigns the resolver as @resolver" do
        resolver = Resolver.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Resolver.any_instance.stub(:save).and_return(false)
        put :update, {:id => resolver.to_param, :resolver => { "device" => "invalid value" }}, valid_session
        assigns(:resolver).should eq(resolver)
      end

      it "re-renders the 'edit' template" do
        resolver = Resolver.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Resolver.any_instance.stub(:save).and_return(false)
        put :update, {:id => resolver.to_param, :resolver => { "device" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested resolver" do
      resolver = Resolver.create! valid_attributes
      expect {
        delete :destroy, {:id => resolver.to_param}, valid_session
      }.to change(Resolver, :count).by(-1)
    end

    it "redirects to the resolvers list" do
      resolver = Resolver.create! valid_attributes
      delete :destroy, {:id => resolver.to_param}, valid_session
      response.should redirect_to(resolvers_url)
    end
  end

end
